### 24RB1075 小嶋将太郎

In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:
# 準備
N = 3
gamma = 0.9
goal = (2, 2)

states = [(i, j) for i in range(N) for j in range(N)]
actions = {"↑": (-1, 0), "↓": (1, 0), "←": (0, -1), "→": (0, 1)}

In [37]:
# ルール
def next_state(state, action):
    
    x, y = state
    dx, dy = action

    nx, ny = x + dx, y + dy

    if 0 <= nx < N and 0 <= ny < N:
        return (nx, ny)
    else:
        return state
    
def reward(next_state):
    if next_state == goal:
        return 1
    else:
        return 0

In [38]:
# 初期化
V = np.zeros((N, N)) 

# 価値反復の実装
max_iterations = 100
threshold = 1e-6

print("【価値反復の結果】")
for iteration in range(max_iterations):

    V_new = np.copy(V)
    V_new[goal] = 0

    for state in states:

        if state == goal:
            continue
        
        best_value = -float("inf")

        for action in actions.values():
            next_s = next_state(state, action)
            r = reward(next_s)
            value = r + gamma * V[next_s]

            if value > best_value:
                best_value = value
            
        V_new[state] = best_value
    
    print(f"V{iteration + 1}:")
    print(np.round(V_new, 3))
    print()

    if np.max(np.abs(V_new - V)) < threshold:
        V = V_new
        print("〜〜〜収束〜〜〜")
        break

    V = V_new

【価値反復の結果】
V1:
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

V2:
[[0.  0.  0.9]
 [0.  0.9 1. ]
 [0.9 1.  0. ]]

V3:
[[0.   0.81 0.9 ]
 [0.81 0.9  1.  ]
 [0.9  1.   0.  ]]

V4:
[[0.729 0.81  0.9  ]
 [0.81  0.9   1.   ]
 [0.9   1.    0.   ]]

V5:
[[0.729 0.81  0.9  ]
 [0.81  0.9   1.   ]
 [0.9   1.    0.   ]]

〜〜〜収束〜〜〜


In [39]:
policy = {}

for state in states:

    if state == goal:
        policy[state] = "G"
        continue

    best_value = -float("inf")
    best_action = None

    for action_name, action in actions.items():
        next_s = next_state(state, action)
        r = reward(next_s)
        value = r + gamma * V[next_s]

        if value > best_value:
            best_value = value
            best_action = action_name
    
    policy[state] = best_action       

In [42]:
print("【収束した価値関数 V*】")
print(np.round(V, 3))
print()

print("【貪欲方策】")
for i in range(N):
    for j in range(N):
        print(policy[(i, j)], end=" ")
    print()

【収束した価値関数 V*】
[[0.729 0.81  0.9  ]
 [0.81  0.9   1.   ]
 [0.9   1.    0.   ]]

【貪欲方策】
↓ ↓ ↓ 
↓ ↓ ↓ 
→ → G 


In [41]:
theory = np.zeros((N, N))

for i in range(N):
    for j in range(N):

        if (i, j) == goal:
            theory[i, j] = 0
        else:
            d = abs(goal[0] - i) + abs(goal[1] - j)
            theory[i, j] = gamma ** (d - 1)

print("【価値反復の結果】")
print(np.round(V, 3))

print("\n【理論値】")
print(np.round(theory, 3))

【価値反復の結果】
[[0.729 0.81  0.9  ]
 [0.81  0.9   1.   ]
 [0.9   1.    0.   ]]

【理論値】
[[0.729 0.81  0.9  ]
 [0.81  0.9   1.   ]
 [0.9   1.    0.   ]]


### 考察
価値反復法を実装し、各反復で価値関数がどのように更新されるかを確認した。反復を重ねるごとにゴールから徐々に伝播していく様子が分かり、価値反復法の仕組みを理解することができた。3×3のグリッドワールドでは、5回程度の反復で収束しており、状態数が少ない問題では効率的に最適価値関数を求められた。

### AIの使用
価値反復法のループ処理や貪欲豊作の可視化の実装において助言を受けた。